apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-craft-comments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-craft-comments
  template:
    metadata:
      labels:
        app: content-craft-comments
    spec:
      containers:
        - name: content-craft-comments
          image: content-craft-comments:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: comments-config-map
                  key: host
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: comments-config-map
                  key: dbName
            - name: MONGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: comments-secrets
                  key: username
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comments-secrets
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: content-craft-comments-svc
spec:
  selector:
    app: content-craft-comments
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort