apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-craft-posts-deployment
spec:
  selector:
    matchLabels:
      app: content-craft-posts-mysql
  replicas: 4
  template:
    metadata:
      labels:
        app: content-craft-posts-mysql
    spec:
      containers:
        - name: content-craft-posts
          image: content-craft-posts:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: posts-config-map
                  key: host
            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: posts-config-map
                  key: dbName
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: posts-secrets
                  key: username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posts-secrets
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: content-craft-posts-svc
spec:
  selector:
    app: content-craft-posts-mysql
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort